// Generated by tauri-specta from src-tauri. Do not edit.
// Regenerate with `cargo test -p calcine` or by running the app in debug.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Calcine's own version and the active backend. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Models in the local GenieX cache (`geniex list`). */
	listModels: () => typedError<LocalModel[], ApiError>(__TAURI_INVOKE("list_models")),
	/**  The installed GenieX runtime (`geniex version`). */
	runtimeInfo: () => typedError<RuntimeInfo, ApiError>(__TAURI_INVOKE("runtime_info")),
};

/* Types */
/**  Error shape returned by every command, typed on the frontend. */
export type ApiError = {
	kind: ErrorKind,
	message: string,
};

export type AppInfo = {
	version: string,
	backend: BackendKind,
};

/**  Which implementation backs the services. */
export type BackendKind = 
/**  The real GenieX CLI. */
"geniex" | 
/**  In-memory fake data (`CALCINE_BACKEND=mock`). */
"mock";

/**  Stable, machine-readable error category exposed to the frontend. */
export type ErrorKind = "runtime_not_found" | "command" | "timeout" | "parse" | "not_implemented" | "io";

/**  A model in the local GenieX cache. */
export type LocalModel = {
	/**  Cache name, e.g. `qualcomm/Qwen3-4B`. Also the API model id. */
	name: string,
	/**  Total size on disk in bytes. */
	sizeBytes: number,
	runtime: Runtime,
	modelType: ModelType,
	/**  Downloaded precisions (`Q4_0`, `W4A16`, …), recommended one first. */
	precisions: string[],
};

/**  Whether a model takes text only or also images and audio. */
export type ModelType = "llm" | "vlm" | 
/**  A type this version of Calcine doesn't know about yet. */
"unknown";

/**  Inference backend a cached model runs on. */
export type Runtime = 
/**  Qualcomm AI Engine Direct: pre-compiled bundles, Hexagon NPU only. */
"qairt" | 
/**  llama.cpp: GGUF models on NPU, GPU or CPU. */
"llama_cpp" | 
/**  A runtime this version of Calcine doesn't know about yet. */
"unknown";

/**  The installed GenieX runtime, as reported by `geniex version`. */
export type RuntimeInfo = {
	/**  GenieX CLI version, e.g. `v0.8.0`. */
	cliVersion: string,
	/**  Bundled Qualcomm AI Engine Direct (QAIRT) version, e.g. `2.45`. */
	qairtVersion: string | null,
	/**  Bundled llama.cpp build hash. */
	llamaCppHash: string | null,
	/**  Absolute path of the `geniex` executable. */
	binaryPath: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

