// Generated by tauri-specta from src-tauri. Do not edit.
// Regenerate with `cargo test -p calcine` or by running the app in debug.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Calcine's own version and the active backend. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Models in the local GenieX cache (`geniex list`). */
	listModels: () => typedError<LocalModel[], ApiError>(__TAURI_INVOKE("list_models")),
	/**  Delete whole models or single precisions (`geniex remove`). */
	removeModels: (keys: ModelKey[]) => typedError<null, ApiError>(__TAURI_INVOKE("remove_models", { keys })),
	/**  Understand a pasted model name or link, to preview it before downloading. */
	parseModelReference: (input: string) => typedError<ModelReference, ApiError>(__TAURI_INVOKE("parse_model_reference", { input })),
	/**  Start a download in the background. Progress arrives as `JobUpdated` events. */
	pullModel: (request: PullRequest) => typedError<number, ApiError>(__TAURI_INVOKE("pull_model", { request })),
	/**  Qualcomm AI Hub models with an NPU build (`geniex model list [--all]`). */
	aihubCatalog: (allChipsets: boolean) => typedError<HubCatalog, ApiError>(__TAURI_INVOKE("aihub_catalog", { allChipsets })),
	/**  The installed GenieX runtime (`geniex version`). */
	runtimeInfo: () => typedError<RuntimeInfo, ApiError>(__TAURI_INVOKE("runtime_info")),
	/**  The Snapdragon chipset GenieX targets (`geniex config get chipset`). */
	chipset: () => typedError<string | null, ApiError>(__TAURI_INVOKE("chipset")),
	/**  CPU, memory, NPU/GPU and free space for the model cache. */
	hardwareInfo: () => typedError<HardwareInfo, ApiError>(__TAURI_INVOKE("hardware_info")),
	/**  Every known job, newest first. */
	listJobs: () => __TAURI_INVOKE<Job[]>("list_jobs"),
	/**  Ask a running job to stop. Returns `false` if it already finished. */
	cancelJob: (id: number) => __TAURI_INVOKE<boolean>("cancel_job", { id }),
	/**  Remove a finished job from the list. */
	dismissJob: (id: number) => __TAURI_INVOKE<boolean>("dismiss_job", { id }),
	gatewayStatus: () => __TAURI_INVOKE<GatewayStatus>("gateway_status"),
	gatewayConnection: () => __TAURI_INVOKE<GatewayConnection>("gateway_connection"),
	/**  Start GenieX now instead of on the first request. */
	startServer: () => typedError<null, ApiError>(__TAURI_INVOKE("start_server")),
	stopServer: () => typedError<null, ApiError>(__TAURI_INVOKE("stop_server")),
	/**  Recent output of `geniex serve`. */
	serverLogs: () => __TAURI_INVOKE<string[]>("server_logs"),
	setRequireApiKey: (require: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("set_require_api_key", { require })),
	/**  Recent API requests, newest first. */
	listRequests: () => __TAURI_INVOKE<RequestEntry[]>("list_requests"),
	listApiKeys: () => __TAURI_INVOKE<ApiKeyInfo[]>("list_api_keys"),
	/**  Create a key. The token is returned once and never stored in clear. */
	createApiKey: (request: NewApiKey) => typedError<CreatedApiKey, ApiError>(__TAURI_INVOKE("create_api_key", { request })),
	revokeApiKey: (id: string) => typedError<boolean, ApiError>(__TAURI_INVOKE("revoke_api_key", { id })),
};

/** Events */
export const events = {
	gatewayUpdated: makeEvent<GatewayUpdated>("gateway-updated"),
	jobUpdated: makeEvent<JobUpdated>("job-updated"),
	requestLogged: makeEvent<RequestLogged>("request-logged"),
};

/* Types */
export type Accelerator = {
	unit: ComputeUnit,
	name: string,
	driverVersion: string | null,
};

/**  Error shape returned by every command, typed on the frontend. */
export type ApiError = {
	kind: ErrorKind,
	message: string,
};

/**  A key as shown in the UI (never the secret itself). */
export type ApiKeyInfo = {
	id: string,
	name: string,
	/**  The first characters, to recognize a key: `calcine_3f9a…`. */
	preview: string,
	scopes: KeyScope[],
	/**
	 *  May send local file paths and URLs (images, audio, grammars) for
	 *  GenieX to read. Off by default: it lets the app read any file.
	 */
	allowLocalFiles: boolean,
	createdAtMs: number,
	lastUsedAtMs: number | null,
};

export type AppInfo = {
	version: string,
	backend: BackendKind,
};

/**  Which implementation backs the services. */
export type BackendKind = 
/**  The real GenieX CLI. */
"geniex" | 
/**  In-memory fake data (`CALCINE_BACKEND=mock`). */
"mock";

/**  Hardware a model can run on (the `--compute` flag of GenieX). */
export type ComputeUnit = 
/**  Hexagon NPU. */
"npu" | 
/**  Adreno GPU. */
"gpu" | 
/**  Oryon CPU. */
"cpu" | 
/**  Split between units. */
"hybrid";

/**  A freshly created key. `token` is only ever returned here. */
export type CreatedApiKey = {
	token: string,
	key: ApiKeyInfo,
};

export type DiskSpace = {
	/**  Directory measured (the model cache). */
	path: string,
	totalBytes: number,
	availableBytes: number,
};

/**  Stable, machine-readable error category exposed to the frontend. */
export type ErrorKind = "runtime_not_found" | "command" | "timeout" | "parse" | "invalid_input" | "cancelled" | "not_implemented" | "io";

/**  How Calcine's own UI talks to the gateway. */
export type GatewayConnection = {
	baseUrl: string,
	/**  Per-launch token with full rights. Only given to the app's webview. */
	token: string,
};

/**  What the Server page shows. */
export type GatewayStatus = {
	listening: boolean,
	/**  Base URL apps use, e.g. `http://127.0.0.1:18181/v1`. */
	baseUrl: string,
	/**  Why the gateway isn't listening (port taken, …). */
	error: string | null,
	server: ServerState,
	activeRequests: number,
	queuedRequests: number,
	requireApiKey: boolean,
};

/**  The gateway or the inference server changed state. */
export type GatewayUpdated = GatewayStatus;

/**  What this device offers for inference. */
export type HardwareInfo = {
	cpu: Processor | null,
	memory: MemoryInfo,
	/**  NPUs and GPUs found on the system. */
	accelerators: Accelerator[],
	/**  Space on the drive holding the model cache. */
	modelsDisk: DiskSpace | null,
};

/**  The Qualcomm AI Hub catalog, optionally filtered for one chipset. */
export type HubCatalog = {
	/**  Chipset the list was filtered for (`None` for the full catalog). */
	chipset: string | null,
	models: HubModel[],
};

/**  A model from the Qualcomm AI Hub catalog (`geniex model list`). */
export type HubModel = {
	/**  Name ready to pull, e.g. `qualcomm/Qwen3-4B`. */
	name: string,
	modelType: ModelType,
	/**
	 *  Chipset slugs the model is compiled for (`x-elite`, `8gen3`, …). Only
	 *  filled for the full catalog (`--all`).
	 */
	chipsets: string[],
};

/**  A snapshot of one job, as sent to the UI. */
export type Job = {
	id: number,
	kind: JobKind,
	state: JobState,
	progress: JobProgress | null,
	startedAtMs: number,
	finishedAtMs: number | null,
};

/**  What a job does. */
export type JobKind = 
/**  Downloading a model (`geniex pull`). */
{ type: "pull"; model: string };

export type JobProgress = {
	doneBytes: number,
	totalBytes: number | null,
	bytesPerSecond: number | null,
};

export type JobState = { state: "running" } | { state: "succeeded" } | { state: "cancelled" } | { state: "failed"; message: string };

/**  A job started, progressed or finished. */
export type JobUpdated = Job;

/**  What a key may do. */
export type KeyScope = 
/**  Chat, completions and listing models (`/v1/*`). */
"inference" | 
/**  Download and remove models, read jobs (`/calcine/v1/*`). */
"manage";

/**  A model in the local GenieX cache. */
export type LocalModel = {
	/**  Cache name, e.g. `qualcomm/Qwen3-4B`. Also the API model id. */
	name: string,
	/**  Total size on disk in bytes. */
	sizeBytes: number,
	runtime: Runtime,
	modelType: ModelType,
	/**  Downloaded precisions (`Q4_0`, `W4A16`, …), recommended one first. */
	precisions: string[],
};

export type MemoryInfo = {
	totalBytes: number,
	availableBytes: number,
};

/**  Where GenieX downloads a model from (`--model-hub`). */
export type ModelHub = 
/**  Let GenieX decide from the name. */
"auto" | 
/**  Qualcomm AI Hub (pre-compiled NPU bundles). */
"ai_hub" | "hugging_face" | "model_scope" | "docker_hub";

/**  A model reference, optionally pinned to one precision (`name:precision`). */
export type ModelKey = {
	name: string,
	precision: string | null,
};

/**  A model to download: `name[:precision]` plus the hub it comes from. */
export type ModelReference = {
	/**  Repository name, e.g. `unsloth/Qwen3-0.6B-GGUF` or `ai/gemma3`. */
	name: string,
	/**
	 *  GGUF quantization (`Q4_0`) or Docker tag. `None` lets GenieX pick the
	 *  recommended one.
	 */
	precision: string | null,
	hub: ModelHub,
};

/**  Whether a model takes text only or also images and audio. */
export type ModelType = "llm" | "vlm" | 
/**  A type this version of Calcine doesn't know about yet. */
"unknown";

/**  What to create. */
export type NewApiKey = {
	name: string,
	scopes: KeyScope[],
	allowLocalFiles: boolean,
};

export type Processor = {
	name: string,
	cores: number,
};

/**  A download request. */
export type PullRequest = {
	reference: ModelReference,
	/**  Override GenieX's LLM/VLM detection. */
	modelType: ModelType | null,
};

export type RequestEntry = {
	id: number,
	startedAtMs: number,
	/**  The API key's name, `Calcine`, or `No key`. */
	client: string,
	method: string,
	path: string,
	model: string | null,
	stream: boolean,
	/**  `None` while in flight. */
	status: number | null,
	durationMs: number | null,
	/**  Time until the first streamed bytes. */
	firstTokenMs: number | null,
	promptTokens: number | null,
	completionTokens: number | null,
	tokensPerSecond: number | null,
	error: string | null,
};

/**  An API request started or finished. */
export type RequestLogged = RequestEntry;

/**  Inference backend a cached model runs on. */
export type Runtime = 
/**  Qualcomm AI Engine Direct: pre-compiled bundles, Hexagon NPU only. */
"qairt" | 
/**  llama.cpp: GGUF models on NPU, GPU or CPU. */
"llama_cpp" | 
/**  A runtime this version of Calcine doesn't know about yet. */
"unknown";

/**  The installed GenieX runtime, as reported by `geniex version`. */
export type RuntimeInfo = {
	/**  GenieX CLI version, e.g. `v0.8.0`. */
	cliVersion: string,
	/**  Bundled Qualcomm AI Engine Direct (QAIRT) version, e.g. `2.45`. */
	qairtVersion: string | null,
	/**  Bundled llama.cpp build hash. */
	llamaCppHash: string | null,
	/**  Absolute path of the `geniex` executable. */
	binaryPath: string,
};

/**  Lifecycle of the inference server process. */
export type ServerState = { state: "stopped" } | { state: "starting" } | 
/**  Accepting requests at `url` (loopback, internal port). */
{ state: "ready"; url: string; startedAtMs: number } | 
/**  The process exited or never became ready. */
{ state: "failed"; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

